// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.krt.netty.protobuf2;

public final class MyDataInfo {
    private MyDataInfo() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface MyMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:MyMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
         * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
         * </pre>
         *
         * <code>.MyMessage.DataType type = 1;</code>
         */
        int getTypeValue();

        /**
         * <pre>
         * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
         * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
         * </pre>
         *
         * <code>.MyMessage.DataType type = 1;</code>
         */
        com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType getType();

        /**
         * <code>.Student student = 2;</code>
         */
        boolean hasStudent();

        /**
         * <code>.Student student = 2;</code>
         */
        com.krt.netty.protobuf2.MyDataInfo.Student getStudent();

        /**
         * <code>.Student student = 2;</code>
         */
        com.krt.netty.protobuf2.MyDataInfo.StudentOrBuilder getStudentOrBuilder();

        /**
         * <code>.Worker worker = 3;</code>
         */
        boolean hasWorker();

        /**
         * <code>.Worker worker = 3;</code>
         */
        com.krt.netty.protobuf2.MyDataInfo.Worker getWorker();

        /**
         * <code>.Worker worker = 3;</code>
         */
        com.krt.netty.protobuf2.MyDataInfo.WorkerOrBuilder getWorkerOrBuilder();

        public com.krt.netty.protobuf2.MyDataInfo.MyMessage.BodyCase getBodyCase();
    }

    /**
     * <pre>
     * protobuf可以使用message管理其他的message
     * </pre>
     * <p>
     * Protobuf type {@code MyMessage}
     */
    public static final class MyMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:MyMessage)
            MyMessageOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use MyMessage.newBuilder() to construct.
        private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private MyMessage() {
            type_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private MyMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            int rawValue = input.readEnum();

                            type_ = rawValue;
                            break;
                        }
                        case 18: {
                            com.krt.netty.protobuf2.MyDataInfo.Student.Builder subBuilder = null;
                            if (bodyCase_ == 2) {
                                subBuilder = ((com.krt.netty.protobuf2.MyDataInfo.Student) body_).toBuilder();
                            }
                            body_ =
                                    input.readMessage(com.krt.netty.protobuf2.MyDataInfo.Student.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom((com.krt.netty.protobuf2.MyDataInfo.Student) body_);
                                body_ = subBuilder.buildPartial();
                            }
                            bodyCase_ = 2;
                            break;
                        }
                        case 26: {
                            com.krt.netty.protobuf2.MyDataInfo.Worker.Builder subBuilder = null;
                            if (bodyCase_ == 3) {
                                subBuilder = ((com.krt.netty.protobuf2.MyDataInfo.Worker) body_).toBuilder();
                            }
                            body_ =
                                    input.readMessage(com.krt.netty.protobuf2.MyDataInfo.Worker.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom((com.krt.netty.protobuf2.MyDataInfo.Worker) body_);
                                body_ = subBuilder.buildPartial();
                            }
                            bodyCase_ = 3;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.krt.netty.protobuf2.MyDataInfo.internal_static_MyMessage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.krt.netty.protobuf2.MyDataInfo.internal_static_MyMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.krt.netty.protobuf2.MyDataInfo.MyMessage.class, com.krt.netty.protobuf2.MyDataInfo.MyMessage.Builder.class);
        }

        /**
         * <pre>
         * 定义枚举类型。在proto3中要求enum的编号从0开始
         * </pre>
         * <p>
         * Protobuf enum {@code MyMessage.DataType}
         */
        public enum DataType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>StudentType = 0;</code>
             */
            StudentType(0),
            /**
             * <code>WorkerType = 1;</code>
             */
            WorkerType(1),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>StudentType = 0;</code>
             */
            public static final int StudentType_VALUE = 0;
            /**
             * <code>WorkerType = 1;</code>
             */
            public static final int WorkerType_VALUE = 1;


            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static DataType valueOf(int value) {
                return forNumber(value);
            }

            public static DataType forNumber(int value) {
                switch (value) {
                    case 0:
                        return StudentType;
                    case 1:
                        return WorkerType;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<DataType>
            internalGetValueMap() {
                return internalValueMap;
            }

            private static final com.google.protobuf.Internal.EnumLiteMap<
                    DataType> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
                        public DataType findValueByNumber(int number) {
                            return DataType.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return com.krt.netty.protobuf2.MyDataInfo.MyMessage.getDescriptor().getEnumTypes().get(0);
            }

            private static final DataType[] VALUES = values();

            public static DataType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private DataType(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:MyMessage.DataType)
        }

        private int bodyCase_ = 0;
        private java.lang.Object body_;

        public enum BodyCase
                implements com.google.protobuf.Internal.EnumLite {
            STUDENT(2),
            WORKER(3),
            BODY_NOT_SET(0);
            private final int value;

            private BodyCase(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static BodyCase valueOf(int value) {
                return forNumber(value);
            }

            public static BodyCase forNumber(int value) {
                switch (value) {
                    case 2:
                        return STUDENT;
                    case 3:
                        return WORKER;
                    case 0:
                        return BODY_NOT_SET;
                    default:
                        return null;
                }
            }

            public int getNumber() {
                return this.value;
            }
        }

        ;

        public BodyCase
        getBodyCase() {
            return BodyCase.forNumber(
                    bodyCase_);
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;

        /**
         * <pre>
         * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
         * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
         * </pre>
         *
         * <code>.MyMessage.DataType type = 1;</code>
         */
        public int getTypeValue() {
            return type_;
        }

        /**
         * <pre>
         * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
         * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
         * </pre>
         *
         * <code>.MyMessage.DataType type = 1;</code>
         */
        public com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType getType() {
            @SuppressWarnings("deprecation")
            com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType result = com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType.valueOf(type_);
            return result == null ? com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType.UNRECOGNIZED : result;
        }

        public static final int STUDENT_FIELD_NUMBER = 2;

        /**
         * <code>.Student student = 2;</code>
         */
        public boolean hasStudent() {
            return bodyCase_ == 2;
        }

        /**
         * <code>.Student student = 2;</code>
         */
        public com.krt.netty.protobuf2.MyDataInfo.Student getStudent() {
            if (bodyCase_ == 2) {
                return (com.krt.netty.protobuf2.MyDataInfo.Student) body_;
            }
            return com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
        }

        /**
         * <code>.Student student = 2;</code>
         */
        public com.krt.netty.protobuf2.MyDataInfo.StudentOrBuilder getStudentOrBuilder() {
            if (bodyCase_ == 2) {
                return (com.krt.netty.protobuf2.MyDataInfo.Student) body_;
            }
            return com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
        }

        public static final int WORKER_FIELD_NUMBER = 3;

        /**
         * <code>.Worker worker = 3;</code>
         */
        public boolean hasWorker() {
            return bodyCase_ == 3;
        }

        /**
         * <code>.Worker worker = 3;</code>
         */
        public com.krt.netty.protobuf2.MyDataInfo.Worker getWorker() {
            if (bodyCase_ == 3) {
                return (com.krt.netty.protobuf2.MyDataInfo.Worker) body_;
            }
            return com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
        }

        /**
         * <code>.Worker worker = 3;</code>
         */
        public com.krt.netty.protobuf2.MyDataInfo.WorkerOrBuilder getWorkerOrBuilder() {
            if (bodyCase_ == 3) {
                return (com.krt.netty.protobuf2.MyDataInfo.Worker) body_;
            }
            return com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (type_ != com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType.StudentType.getNumber()) {
                output.writeEnum(1, type_);
            }
            if (bodyCase_ == 2) {
                output.writeMessage(2, (com.krt.netty.protobuf2.MyDataInfo.Student) body_);
            }
            if (bodyCase_ == 3) {
                output.writeMessage(3, (com.krt.netty.protobuf2.MyDataInfo.Worker) body_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (type_ != com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType.StudentType.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_);
            }
            if (bodyCase_ == 2) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, (com.krt.netty.protobuf2.MyDataInfo.Student) body_);
            }
            if (bodyCase_ == 3) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, (com.krt.netty.protobuf2.MyDataInfo.Worker) body_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.krt.netty.protobuf2.MyDataInfo.MyMessage)) {
                return super.equals(obj);
            }
            com.krt.netty.protobuf2.MyDataInfo.MyMessage other = (com.krt.netty.protobuf2.MyDataInfo.MyMessage) obj;

            boolean result = true;
            result = result && type_ == other.type_;
            result = result && getBodyCase().equals(
                    other.getBodyCase());
            if (!result) return false;
            switch (bodyCase_) {
                case 2:
                    result = result && getStudent()
                            .equals(other.getStudent());
                    break;
                case 3:
                    result = result && getWorker()
                            .equals(other.getWorker());
                    break;
                case 0:
                default:
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + type_;
            switch (bodyCase_) {
                case 2:
                    hash = (37 * hash) + STUDENT_FIELD_NUMBER;
                    hash = (53 * hash) + getStudent().hashCode();
                    break;
                case 3:
                    hash = (37 * hash) + WORKER_FIELD_NUMBER;
                    hash = (53 * hash) + getWorker().hashCode();
                    break;
                case 0:
                default:
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.krt.netty.protobuf2.MyDataInfo.MyMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * protobuf可以使用message管理其他的message
         * </pre>
         * <p>
         * Protobuf type {@code MyMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:MyMessage)
                com.krt.netty.protobuf2.MyDataInfo.MyMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_MyMessage_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_MyMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.krt.netty.protobuf2.MyDataInfo.MyMessage.class, com.krt.netty.protobuf2.MyDataInfo.MyMessage.Builder.class);
            }

            // Construct using com.krt.netty.protobuf2.MyDataInfo.MyMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                type_ = 0;

                bodyCase_ = 0;
                body_ = null;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_MyMessage_descriptor;
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.MyMessage getDefaultInstanceForType() {
                return com.krt.netty.protobuf2.MyDataInfo.MyMessage.getDefaultInstance();
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.MyMessage build() {
                com.krt.netty.protobuf2.MyDataInfo.MyMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.MyMessage buildPartial() {
                com.krt.netty.protobuf2.MyDataInfo.MyMessage result = new com.krt.netty.protobuf2.MyDataInfo.MyMessage(this);
                result.type_ = type_;
                if (bodyCase_ == 2) {
                    if (studentBuilder_ == null) {
                        result.body_ = body_;
                    } else {
                        result.body_ = studentBuilder_.build();
                    }
                }
                if (bodyCase_ == 3) {
                    if (workerBuilder_ == null) {
                        result.body_ = body_;
                    } else {
                        result.body_ = workerBuilder_.build();
                    }
                }
                result.bodyCase_ = bodyCase_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.krt.netty.protobuf2.MyDataInfo.MyMessage) {
                    return mergeFrom((com.krt.netty.protobuf2.MyDataInfo.MyMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.krt.netty.protobuf2.MyDataInfo.MyMessage other) {
                if (other == com.krt.netty.protobuf2.MyDataInfo.MyMessage.getDefaultInstance()) return this;
                if (other.type_ != 0) {
                    setTypeValue(other.getTypeValue());
                }
                switch (other.getBodyCase()) {
                    case STUDENT: {
                        mergeStudent(other.getStudent());
                        break;
                    }
                    case WORKER: {
                        mergeWorker(other.getWorker());
                        break;
                    }
                    case BODY_NOT_SET: {
                        break;
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.krt.netty.protobuf2.MyDataInfo.MyMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.krt.netty.protobuf2.MyDataInfo.MyMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bodyCase_ = 0;
            private java.lang.Object body_;

            public BodyCase
            getBodyCase() {
                return BodyCase.forNumber(
                        bodyCase_);
            }

            public Builder clearBody() {
                bodyCase_ = 0;
                body_ = null;
                onChanged();
                return this;
            }


            private int type_ = 0;

            /**
             * <pre>
             * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
             * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
             * </pre>
             *
             * <code>.MyMessage.DataType type = 1;</code>
             */
            public int getTypeValue() {
                return type_;
            }

            /**
             * <pre>
             * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
             * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
             * </pre>
             *
             * <code>.MyMessage.DataType type = 1;</code>
             */
            public Builder setTypeValue(int value) {
                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
             * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
             * </pre>
             *
             * <code>.MyMessage.DataType type = 1;</code>
             */
            public com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType getType() {
                @SuppressWarnings("deprecation")
                com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType result = com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType.valueOf(type_);
                return result == null ? com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType.UNRECOGNIZED : result;
            }

            /**
             * <pre>
             * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
             * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
             * </pre>
             *
             * <code>.MyMessage.DataType type = 1;</code>
             */
            public Builder setType(com.krt.netty.protobuf2.MyDataInfo.MyMessage.DataType value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 用type来标识传的是哪一个枚举类型。即通过type类型我们就可以判断当前对象是哪一个对象。
             * 如果type=StudentType表示该对象是Student的实例，如果type=WorkerType则为Worker的实例
             * </pre>
             *
             * <code>.MyMessage.DataType type = 1;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.SingleFieldBuilderV3<
                    com.krt.netty.protobuf2.MyDataInfo.Student, com.krt.netty.protobuf2.MyDataInfo.Student.Builder, com.krt.netty.protobuf2.MyDataInfo.StudentOrBuilder> studentBuilder_;

            /**
             * <code>.Student student = 2;</code>
             */
            public boolean hasStudent() {
                return bodyCase_ == 2;
            }

            /**
             * <code>.Student student = 2;</code>
             */
            public com.krt.netty.protobuf2.MyDataInfo.Student getStudent() {
                if (studentBuilder_ == null) {
                    if (bodyCase_ == 2) {
                        return (com.krt.netty.protobuf2.MyDataInfo.Student) body_;
                    }
                    return com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
                } else {
                    if (bodyCase_ == 2) {
                        return studentBuilder_.getMessage();
                    }
                    return com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
                }
            }

            /**
             * <code>.Student student = 2;</code>
             */
            public Builder setStudent(com.krt.netty.protobuf2.MyDataInfo.Student value) {
                if (studentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    body_ = value;
                    onChanged();
                } else {
                    studentBuilder_.setMessage(value);
                }
                bodyCase_ = 2;
                return this;
            }

            /**
             * <code>.Student student = 2;</code>
             */
            public Builder setStudent(
                    com.krt.netty.protobuf2.MyDataInfo.Student.Builder builderForValue) {
                if (studentBuilder_ == null) {
                    body_ = builderForValue.build();
                    onChanged();
                } else {
                    studentBuilder_.setMessage(builderForValue.build());
                }
                bodyCase_ = 2;
                return this;
            }

            /**
             * <code>.Student student = 2;</code>
             */
            public Builder mergeStudent(com.krt.netty.protobuf2.MyDataInfo.Student value) {
                if (studentBuilder_ == null) {
                    if (bodyCase_ == 2 &&
                            body_ != com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance()) {
                        body_ = com.krt.netty.protobuf2.MyDataInfo.Student.newBuilder((com.krt.netty.protobuf2.MyDataInfo.Student) body_)
                                .mergeFrom(value).buildPartial();
                    } else {
                        body_ = value;
                    }
                    onChanged();
                } else {
                    if (bodyCase_ == 2) {
                        studentBuilder_.mergeFrom(value);
                    }
                    studentBuilder_.setMessage(value);
                }
                bodyCase_ = 2;
                return this;
            }

            /**
             * <code>.Student student = 2;</code>
             */
            public Builder clearStudent() {
                if (studentBuilder_ == null) {
                    if (bodyCase_ == 2) {
                        bodyCase_ = 0;
                        body_ = null;
                        onChanged();
                    }
                } else {
                    if (bodyCase_ == 2) {
                        bodyCase_ = 0;
                        body_ = null;
                    }
                    studentBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>.Student student = 2;</code>
             */
            public com.krt.netty.protobuf2.MyDataInfo.Student.Builder getStudentBuilder() {
                return getStudentFieldBuilder().getBuilder();
            }

            /**
             * <code>.Student student = 2;</code>
             */
            public com.krt.netty.protobuf2.MyDataInfo.StudentOrBuilder getStudentOrBuilder() {
                if ((bodyCase_ == 2) && (studentBuilder_ != null)) {
                    return studentBuilder_.getMessageOrBuilder();
                } else {
                    if (bodyCase_ == 2) {
                        return (com.krt.netty.protobuf2.MyDataInfo.Student) body_;
                    }
                    return com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
                }
            }

            /**
             * <code>.Student student = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.krt.netty.protobuf2.MyDataInfo.Student, com.krt.netty.protobuf2.MyDataInfo.Student.Builder, com.krt.netty.protobuf2.MyDataInfo.StudentOrBuilder>
            getStudentFieldBuilder() {
                if (studentBuilder_ == null) {
                    if (!(bodyCase_ == 2)) {
                        body_ = com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
                    }
                    studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.krt.netty.protobuf2.MyDataInfo.Student, com.krt.netty.protobuf2.MyDataInfo.Student.Builder, com.krt.netty.protobuf2.MyDataInfo.StudentOrBuilder>(
                            (com.krt.netty.protobuf2.MyDataInfo.Student) body_,
                            getParentForChildren(),
                            isClean());
                    body_ = null;
                }
                bodyCase_ = 2;
                onChanged();
                ;
                return studentBuilder_;
            }

            private com.google.protobuf.SingleFieldBuilderV3<
                    com.krt.netty.protobuf2.MyDataInfo.Worker, com.krt.netty.protobuf2.MyDataInfo.Worker.Builder, com.krt.netty.protobuf2.MyDataInfo.WorkerOrBuilder> workerBuilder_;

            /**
             * <code>.Worker worker = 3;</code>
             */
            public boolean hasWorker() {
                return bodyCase_ == 3;
            }

            /**
             * <code>.Worker worker = 3;</code>
             */
            public com.krt.netty.protobuf2.MyDataInfo.Worker getWorker() {
                if (workerBuilder_ == null) {
                    if (bodyCase_ == 3) {
                        return (com.krt.netty.protobuf2.MyDataInfo.Worker) body_;
                    }
                    return com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
                } else {
                    if (bodyCase_ == 3) {
                        return workerBuilder_.getMessage();
                    }
                    return com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
                }
            }

            /**
             * <code>.Worker worker = 3;</code>
             */
            public Builder setWorker(com.krt.netty.protobuf2.MyDataInfo.Worker value) {
                if (workerBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    body_ = value;
                    onChanged();
                } else {
                    workerBuilder_.setMessage(value);
                }
                bodyCase_ = 3;
                return this;
            }

            /**
             * <code>.Worker worker = 3;</code>
             */
            public Builder setWorker(
                    com.krt.netty.protobuf2.MyDataInfo.Worker.Builder builderForValue) {
                if (workerBuilder_ == null) {
                    body_ = builderForValue.build();
                    onChanged();
                } else {
                    workerBuilder_.setMessage(builderForValue.build());
                }
                bodyCase_ = 3;
                return this;
            }

            /**
             * <code>.Worker worker = 3;</code>
             */
            public Builder mergeWorker(com.krt.netty.protobuf2.MyDataInfo.Worker value) {
                if (workerBuilder_ == null) {
                    if (bodyCase_ == 3 &&
                            body_ != com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance()) {
                        body_ = com.krt.netty.protobuf2.MyDataInfo.Worker.newBuilder((com.krt.netty.protobuf2.MyDataInfo.Worker) body_)
                                .mergeFrom(value).buildPartial();
                    } else {
                        body_ = value;
                    }
                    onChanged();
                } else {
                    if (bodyCase_ == 3) {
                        workerBuilder_.mergeFrom(value);
                    }
                    workerBuilder_.setMessage(value);
                }
                bodyCase_ = 3;
                return this;
            }

            /**
             * <code>.Worker worker = 3;</code>
             */
            public Builder clearWorker() {
                if (workerBuilder_ == null) {
                    if (bodyCase_ == 3) {
                        bodyCase_ = 0;
                        body_ = null;
                        onChanged();
                    }
                } else {
                    if (bodyCase_ == 3) {
                        bodyCase_ = 0;
                        body_ = null;
                    }
                    workerBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>.Worker worker = 3;</code>
             */
            public com.krt.netty.protobuf2.MyDataInfo.Worker.Builder getWorkerBuilder() {
                return getWorkerFieldBuilder().getBuilder();
            }

            /**
             * <code>.Worker worker = 3;</code>
             */
            public com.krt.netty.protobuf2.MyDataInfo.WorkerOrBuilder getWorkerOrBuilder() {
                if ((bodyCase_ == 3) && (workerBuilder_ != null)) {
                    return workerBuilder_.getMessageOrBuilder();
                } else {
                    if (bodyCase_ == 3) {
                        return (com.krt.netty.protobuf2.MyDataInfo.Worker) body_;
                    }
                    return com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
                }
            }

            /**
             * <code>.Worker worker = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.krt.netty.protobuf2.MyDataInfo.Worker, com.krt.netty.protobuf2.MyDataInfo.Worker.Builder, com.krt.netty.protobuf2.MyDataInfo.WorkerOrBuilder>
            getWorkerFieldBuilder() {
                if (workerBuilder_ == null) {
                    if (!(bodyCase_ == 3)) {
                        body_ = com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
                    }
                    workerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.krt.netty.protobuf2.MyDataInfo.Worker, com.krt.netty.protobuf2.MyDataInfo.Worker.Builder, com.krt.netty.protobuf2.MyDataInfo.WorkerOrBuilder>(
                            (com.krt.netty.protobuf2.MyDataInfo.Worker) body_,
                            getParentForChildren(),
                            isClean());
                    body_ = null;
                }
                bodyCase_ = 3;
                onChanged();
                ;
                return workerBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:MyMessage)
        }

        // @@protoc_insertion_point(class_scope:MyMessage)
        private static final com.krt.netty.protobuf2.MyDataInfo.MyMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.krt.netty.protobuf2.MyDataInfo.MyMessage();
        }

        public static com.krt.netty.protobuf2.MyDataInfo.MyMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<MyMessage>
                PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
            @java.lang.Override
            public MyMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new MyMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<MyMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MyMessage> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.krt.netty.protobuf2.MyDataInfo.MyMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface StudentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Student)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>string name = 2;</code>
         */
        java.lang.String getName();

        /**
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();
    }

    /**
     * <pre>
     * Student内部类属性
     * </pre>
     * <p>
     * Protobuf type {@code Student}
     */
    public static final class Student extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Student)
            StudentOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Student.newBuilder() to construct.
        private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Student() {
            id_ = 0;
            name_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Student(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.krt.netty.protobuf2.MyDataInfo.internal_static_Student_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.krt.netty.protobuf2.MyDataInfo.internal_static_Student_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.krt.netty.protobuf2.MyDataInfo.Student.class, com.krt.netty.protobuf2.MyDataInfo.Student.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private int id_;

        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;

        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.krt.netty.protobuf2.MyDataInfo.Student)) {
                return super.equals(obj);
            }
            com.krt.netty.protobuf2.MyDataInfo.Student other = (com.krt.netty.protobuf2.MyDataInfo.Student) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getName()
                    .equals(other.getName());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.krt.netty.protobuf2.MyDataInfo.Student prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * Student内部类属性
         * </pre>
         * <p>
         * Protobuf type {@code Student}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Student)
                com.krt.netty.protobuf2.MyDataInfo.StudentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_Student_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_Student_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.krt.netty.protobuf2.MyDataInfo.Student.class, com.krt.netty.protobuf2.MyDataInfo.Student.Builder.class);
            }

            // Construct using com.krt.netty.protobuf2.MyDataInfo.Student.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0;

                name_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_Student_descriptor;
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.Student getDefaultInstanceForType() {
                return com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.Student build() {
                com.krt.netty.protobuf2.MyDataInfo.Student result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.Student buildPartial() {
                com.krt.netty.protobuf2.MyDataInfo.Student result = new com.krt.netty.protobuf2.MyDataInfo.Student(this);
                result.id_ = id_;
                result.name_ = name_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.krt.netty.protobuf2.MyDataInfo.Student) {
                    return mergeFrom((com.krt.netty.protobuf2.MyDataInfo.Student) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.krt.netty.protobuf2.MyDataInfo.Student other) {
                if (other == com.krt.netty.protobuf2.MyDataInfo.Student.getDefaultInstance()) return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.krt.netty.protobuf2.MyDataInfo.Student parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.krt.netty.protobuf2.MyDataInfo.Student) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int id_;

            /**
             * <code>int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Student)
        }

        // @@protoc_insertion_point(class_scope:Student)
        private static final com.krt.netty.protobuf2.MyDataInfo.Student DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.krt.netty.protobuf2.MyDataInfo.Student();
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Student getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Student>
                PARSER = new com.google.protobuf.AbstractParser<Student>() {
            @java.lang.Override
            public Student parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Student(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Student> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Student> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.krt.netty.protobuf2.MyDataInfo.Student getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface WorkerOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Worker)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         */
        java.lang.String getName();

        /**
         * <code>string name = 1;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>int32 age = 2;</code>
         */
        int getAge();
    }

    /**
     * <pre>
     * Worker内部类属性
     * </pre>
     * <p>
     * Protobuf type {@code Worker}
     */
    public static final class Worker extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Worker)
            WorkerOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Worker.newBuilder() to construct.
        private Worker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Worker() {
            name_ = "";
            age_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Worker(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 16: {

                            age_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.krt.netty.protobuf2.MyDataInfo.internal_static_Worker_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.krt.netty.protobuf2.MyDataInfo.internal_static_Worker_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.krt.netty.protobuf2.MyDataInfo.Worker.class, com.krt.netty.protobuf2.MyDataInfo.Worker.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;

        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AGE_FIELD_NUMBER = 2;
        private int age_;

        /**
         * <code>int32 age = 2;</code>
         */
        public int getAge() {
            return age_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (age_ != 0) {
                output.writeInt32(2, age_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, age_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.krt.netty.protobuf2.MyDataInfo.Worker)) {
                return super.equals(obj);
            }
            com.krt.netty.protobuf2.MyDataInfo.Worker other = (com.krt.netty.protobuf2.MyDataInfo.Worker) obj;

            boolean result = true;
            result = result && getName()
                    .equals(other.getName());
            result = result && (getAge()
                    == other.getAge());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.krt.netty.protobuf2.MyDataInfo.Worker prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * Worker内部类属性
         * </pre>
         * <p>
         * Protobuf type {@code Worker}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Worker)
                com.krt.netty.protobuf2.MyDataInfo.WorkerOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_Worker_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_Worker_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.krt.netty.protobuf2.MyDataInfo.Worker.class, com.krt.netty.protobuf2.MyDataInfo.Worker.Builder.class);
            }

            // Construct using com.krt.netty.protobuf2.MyDataInfo.Worker.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                name_ = "";

                age_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.krt.netty.protobuf2.MyDataInfo.internal_static_Worker_descriptor;
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.Worker getDefaultInstanceForType() {
                return com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.Worker build() {
                com.krt.netty.protobuf2.MyDataInfo.Worker result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.krt.netty.protobuf2.MyDataInfo.Worker buildPartial() {
                com.krt.netty.protobuf2.MyDataInfo.Worker result = new com.krt.netty.protobuf2.MyDataInfo.Worker(this);
                result.name_ = name_;
                result.age_ = age_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.krt.netty.protobuf2.MyDataInfo.Worker) {
                    return mergeFrom((com.krt.netty.protobuf2.MyDataInfo.Worker) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.krt.netty.protobuf2.MyDataInfo.Worker other) {
                if (other == com.krt.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance()) return this;
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.krt.netty.protobuf2.MyDataInfo.Worker parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.krt.netty.protobuf2.MyDataInfo.Worker) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>string name = 1;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private int age_;

            /**
             * <code>int32 age = 2;</code>
             */
            public int getAge() {
                return age_;
            }

            /**
             * <code>int32 age = 2;</code>
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 age = 2;</code>
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Worker)
        }

        // @@protoc_insertion_point(class_scope:Worker)
        private static final com.krt.netty.protobuf2.MyDataInfo.Worker DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.krt.netty.protobuf2.MyDataInfo.Worker();
        }

        public static com.krt.netty.protobuf2.MyDataInfo.Worker getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Worker>
                PARSER = new com.google.protobuf.AbstractParser<Worker>() {
            @java.lang.Override
            public Worker parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Worker(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Worker> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Worker> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.krt.netty.protobuf2.MyDataInfo.Worker getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_MyMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_MyMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Student_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Student_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Worker_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Worker_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\rStudent.proto\"\233\001\n\tMyMessage\022!\n\004type\030\001 " +
                        "\001(\0162\023.MyMessage.DataType\022\033\n\007student\030\002 \001(" +
                        "\0132\010.StudentH\000\022\031\n\006worker\030\003 \001(\0132\007.WorkerH\000" +
                        "\"+\n\010DataType\022\017\n\013StudentType\020\000\022\016\n\nWorkerT" +
                        "ype\020\001B\006\n\004body\"#\n\007Student\022\n\n\002id\030\001 \001(\005\022\014\n\004" +
                        "name\030\002 \001(\t\"#\n\006Worker\022\014\n\004name\030\001 \001(\t\022\013\n\003ag" +
                        "e\030\002 \001(\005B\'\n\027com.krt.netty.protobuf2B\nMyDa" +
                        "taInfoH\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_MyMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_MyMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_MyMessage_descriptor,
                new java.lang.String[]{"Type", "Student", "Worker", "Body",});
        internal_static_Student_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Student_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Student_descriptor,
                new java.lang.String[]{"Id", "Name",});
        internal_static_Worker_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Worker_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Worker_descriptor,
                new java.lang.String[]{"Name", "Age",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
